title: William Entriken Blog
subtitle: Analysis of all
description: Essays by William Entriken

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: "William Entriken"
      title: ~
      description: ~
      updates: ~ # Array of date/changes objects

# Cause a build to fail if there is a YAML syntax error in a page's front matter.
strict_front_matter: true

# https://jekyllrb.com/docs/configuration/liquid/
liquid:
  error_mode: strict
  #strict_variables: true
  strict_filters: true

permalink: /:categories/:year/:month/:day/:title