title: William Entriken Blog
subtitle: Analysis of all
description: Essays by William Entriken

defaults:
  - scope:
      path: ""
      type: posts
    values:
      # title: ~ # No default, must be explicitly set each time
      # tags: [] # No default, must be explicitly set each time
      updates: ~ # Array of date/changes objects
      authors: [William Entriken]
      old-link: ~
      comments: ~
      affiliate-link: false
      description: ~
  - scope:
      path: "_redirects"
    values:
      layout: redirect

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - scripts


include:
  - _redirects

# Cause a build to fail if there is a YAML syntax error in a page's front matter.
strict_front_matter: true

# https://jekyllrb.com/docs/configuration/liquid/
liquid:
  error_mode: strict
  #strict_variables: true
  strict_filters: true

permalink: /:categories/:title